// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using kalibre_api;

#nullable disable

namespace kalibre_api.Migrations
{
    [DbContext(typeof(KalibreContext))]
    [Migration("20240413112709_Initial")]
    partial class Initial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.HasPostgresExtension(modelBuilder, "pg_catalog", "adminpack");
            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("kalibre_api.Despesa", b =>
                {
                    b.Property<int>("DespesaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("despesaId");

                    NpgsqlPropertyBuilderExtensions.UseIdentityAlwaysColumn(b.Property<int>("DespesaId"));
                    NpgsqlPropertyBuilderExtensions.HasIdentityOptions(b.Property<int>("DespesaId"), null, null, 0L, null, null, null);

                    b.Property<DateTime>("Data")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("data");

                    b.Property<decimal>("Valor")
                        .HasColumnType("money")
                        .HasColumnName("valor");

                    b.HasKey("DespesaId")
                        .HasName("despesas_pkey");

                    b.ToTable("despesas", (string)null);
                });

            modelBuilder.Entity("kalibre_api.Receita", b =>
                {
                    b.Property<int>("Receitaid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("receitaid");

                    NpgsqlPropertyBuilderExtensions.UseIdentityAlwaysColumn(b.Property<int>("Receitaid"));
                    NpgsqlPropertyBuilderExtensions.HasIdentityOptions(b.Property<int>("Receitaid"), null, null, 0L, null, null, null);

                    b.Property<DateTime>("Data")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("data");

                    b.Property<decimal>("Valor")
                        .HasColumnType("money")
                        .HasColumnName("valor");

                    b.HasKey("Receitaid")
                        .HasName("receitas_pkey");

                    b.ToTable("receitas", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
